export const GET_CART_DATA_REQUEST = "GET_CART_DATA_REQUEST";
export const GET_CART_DATA_SUCCESS = "GET_CART_DATA_SUCCESS";
export const GET_CART_DATA_ERROR = "GET_CART_DATA_ERROR";

export const DELETE_CART_ITEM_REQUEST = "DELETE_CART_ITEM_REQUEST";
export const DELETE_CART_ITEM_SUCCESS = "DELETE_CART_ITEM_SUCCESS";
export const DELETE_CART_ITEM__ERROR = "DELETE_CART_ITEM__ERROR";

export const PLUS_CART_ITEM_REQUEST = "PLUS_CART_ITEM_REQUEST";
export const PLUS_CART_ITEM_SUCCESS = "PLUS_CART_ITEM_SUCCESS";
export const PLUS_CART_ITEM__ERROR = "PLUS_CART_ITEM__ERROR";


