export const GET_PRODUCTS_DATA_REQUEST ='GET_PRODUCTS_DATA_GET_PRODUCTS_DATA_REQUEST'
export const GET_PRODUCTS_DATA_SUCCESS ='GET_PRODUCTS_DATA_GET_PRODUCTS_DATA_SUCCESS'
export const GET_PRODUCTS_DATA_FAILURE ='GET_PRODUCTS_DATA_GET_PRODUCTS_DATA_FAILURE'

export const GET_SINGLE_PRODUCTS_DATA_REQUEST ='GET_SINGLE_PRODUCTS_DATA_REQUEST'
export const GET_SINGLE_PRODUCTS_DATA_SUCCESS ='GET_SINGLE_PRODUCTS_DATA_SUCCESS'
export const GET_SINGLE_PRODUCTS_DATA_FAILURE ='GET_SINGLE_PRODUCTS_DATA_FAILURE'

export const ADD_CART_DATA_REQUEST ='ADD_CART_DATA_REQUEST'
export const ADD_CART_DATA_SUCCESS ='ADD_CART_DATA_SUCCESS'
export const ADD_CART_DATA_FAILURE ='ADD_CART_DATA_FAILURE'

export const FETCH_CART_SUCCESS='FETCH_CART_SUCCESS'

export const DELETE_CART_DATA_REUEST='DELETE_CART_DATA_REUEST'
export const DELETE_CART_DATA_SUCCESS='DELETE_CART_DATA_SUCCESS'
export const DELETE_CART_DATA_FAILURE='DELETE_CART_DATA_FAILURE'

export const FetchSkinMedicaData="FetchSkinMedicaData"
export const FetchBestSellersData="FetchBestSellersData"
export const FetchNeocutisData=" FetchNeocutisData"
export const FetchTrendingData="FetchTrendingData"
export const FetchNewarraivals="FetchNewarraivals"
export const FetchBlogData="FetchBlogData"